#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_EZhezhiMaobi

#include "Basic.hpp"

#include "ABP_EZhezhiMaobi_classes.hpp"
#include "ABP_EZhezhiMaobi_parameters.hpp"


namespace SDK
{

// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.ExecuteUbergraph_ABP_EZhezhiMaobi
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_EZhezhiMaobi_C::ExecuteUbergraph_ABP_EZhezhiMaobi(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "ExecuteUbergraph_ABP_EZhezhiMaobi");

	Params::ABP_EZhezhiMaobi_C_ExecuteUbergraph_ABP_EZhezhiMaobi Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.OnComponentStart
// (Event, Public, BlueprintEvent)

void UABP_EZhezhiMaobi_C::OnComponentStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "OnComponentStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_EZhezhiMaobi_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "BlueprintUpdateAnimation");

	Params::ABP_EZhezhiMaobi_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_EZhezhiMaobi_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.初始化
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UABP_EZhezhiMaobi_C::初始化()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "初始化");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_EZhezhiMaobi.ABP_EZhezhiMaobi_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_EZhezhiMaobi_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EZhezhiMaobi_C", "AnimGraph");

	Params::ABP_EZhezhiMaobi_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

