#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MO1LiufangzhemanMd00001_NPC

#include "Basic.hpp"

#include "ABP_BaseNPC_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_MO1LiufangzhemanMd00001_NPC.ABP_MO1LiufangzhemanMd00001_NPC_C
// 0x0000 (0x22D0 - 0x22D0)
class UABP_MO1LiufangzhemanMd00001_NPC_C final : public UABP_BaseNPC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_MO1LiufangzhemanMd00001_NPC_C">();
	}
	static class UABP_MO1LiufangzhemanMd00001_NPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_MO1LiufangzhemanMd00001_NPC_C>();
	}
};
static_assert(alignof(UABP_MO1LiufangzhemanMd00001_NPC_C) == 0x000010, "Wrong alignment on UABP_MO1LiufangzhemanMd00001_NPC_C");
static_assert(sizeof(UABP_MO1LiufangzhemanMd00001_NPC_C) == 0x0022D0, "Wrong size on UABP_MO1LiufangzhemanMd00001_NPC_C");

}

