#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ani_VisionlRewardTip_Close

#include "Basic.hpp"

#include "Ani_VisionlRewardTip_Close_classes.hpp"
#include "Ani_VisionlRewardTip_Close_parameters.hpp"


namespace SDK
{

// Function Ani_VisionlRewardTip_Close.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_VisionlRewardTip                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_VisionlRewardTip_Close::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class AUIContainerActor* UiItem_VisionlRewardTip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.UiItem_VisionlRewardTip = UiItem_VisionlRewardTip;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_VisionlRewardTip_Close.SequenceDirector_C.UiItem_VisionlRewardTip_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AUIContainerActor*                UiItem_VisionlRewardTip                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_VisionlRewardTip_Close::USequenceDirector_C::UiItem_VisionlRewardTip_Event_0(class AUIContainerActor* UiItem_VisionlRewardTip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "UiItem_VisionlRewardTip_Event_0");

	Params::SequenceDirector_C_UiItem_VisionlRewardTip_Event_0 Parms{};

	Parms.UiItem_VisionlRewardTip = UiItem_VisionlRewardTip;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ani_VisionlRewardTip_Close.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ani_VisionlRewardTip_Close::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

