#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AttackShake_Chun1

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AttackShake_Chun1.AttackShake_Chun1_C
// 0x0000 (0x01A0 - 0x01A0)
class UAttackShake_Chun1_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AttackShake_Chun1_C">();
	}
	static class UAttackShake_Chun1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAttackShake_Chun1_C>();
	}
};
static_assert(alignof(UAttackShake_Chun1_C) == 0x000010, "Wrong alignment on UAttackShake_Chun1_C");
static_assert(sizeof(UAttackShake_Chun1_C) == 0x0001A0, "Wrong size on UAttackShake_Chun1_C");

}

