#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseVision

#include "Basic.hpp"

#include "BP_BaseVision_classes.hpp"
#include "BP_BaseVision_parameters.hpp"


namespace SDK
{

// Function BP_BaseVision.BP_BaseVision_C.ExecuteUbergraph_BP_BaseVision
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVision_C::ExecuteUbergraph_BP_BaseVision(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "ExecuteUbergraph_BP_BaseVision");

	Params::BP_BaseVision_C_ExecuteUbergraph_BP_BaseVision Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseVision.BP_BaseVision_C.显像缩小
// (BlueprintCallable, BlueprintEvent)

void ABP_BaseVision_C::显像缩小()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "显像缩小");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseVision.BP_BaseVision_C.显像放大
// (BlueprintCallable, BlueprintEvent)

void ABP_BaseVision_C::显像放大()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "显像放大");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseVision.BP_BaseVision_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVision_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "ReceiveTick");

	Params::BP_BaseVision_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseVision.BP_BaseVision_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BaseVision_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseVision.BP_BaseVision_C.获取幻象数据
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSVisionData*                    幻象数据                                               (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)

void ABP_BaseVision_C::获取幻象数据(struct FSVisionData* 幻象数据)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "获取幻象数据");

	Params::BP_BaseVision_C_获取幻象数据 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (幻象数据 != nullptr)
		*幻象数据 = std::move(Parms.幻象数据);
}


// Function BP_BaseVision.BP_BaseVision_C.获取召唤角色
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ATsBaseCharacter_C**              召唤角色                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVision_C::获取召唤角色(class ATsBaseCharacter_C** 召唤角色)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVision_C", "获取召唤角色");

	Params::BP_BaseVision_C_获取召唤角色 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (召唤角色 != nullptr)
		*召唤角色 = Parms.召唤角色;
}

}

