#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomDepthForToon

#include "Basic.hpp"

#include "BP_CustomDepthForToon_classes.hpp"
#include "BP_CustomDepthForToon_parameters.hpp"


namespace SDK
{

// Function BP_CustomDepthForToon.BP_CustomDepthForToon_C.ExecuteUbergraph_BP_CustomDepthForToon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CustomDepthForToon_C::ExecuteUbergraph_BP_CustomDepthForToon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomDepthForToon_C", "ExecuteUbergraph_BP_CustomDepthForToon");

	Params::BP_CustomDepthForToon_C_ExecuteUbergraph_BP_CustomDepthForToon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomDepthForToon.BP_CustomDepthForToon_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CustomDepthForToon_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomDepthForToon_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomDepthForToon.BP_CustomDepthForToon_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_CustomDepthForToon_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomDepthForToon_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomDepthForToon.BP_CustomDepthForToon_C.EnableCustomDepthForToon
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CustomDepthForToon_C::EnableCustomDepthForToon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomDepthForToon_C", "EnableCustomDepthForToon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomDepthForToon.BP_CustomDepthForToon_C.DisableCustomDepthForToon
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CustomDepthForToon_C::DisableCustomDepthForToon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomDepthForToon_C", "DisableCustomDepthForToon");

	UObject::ProcessEvent(Func, nullptr);
}

}

