#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Fx_WayFinding

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Fx_WayFinding.BP_Fx_WayFinding_C
// 0x0030 (0x02E0 - 0x02B0)
class ABP_Fx_WayFinding_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_Fx_WayFinding;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USplineComponent*                       Spline;                                            // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Distance;                                          // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MinFragmentsNum;                                   // 0x02CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Deactivating;                                      // 0x02D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D1[0x3];                                      // 0x02D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DeactiveAlpha;                                     // 0x02D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeactiveAlphaSpeed;                                // 0x02D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Fx_WayFinding(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void EnsureEffect();
	void StopEffect();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Fx_WayFinding_C">();
	}
	static class ABP_Fx_WayFinding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Fx_WayFinding_C>();
	}
};
static_assert(alignof(ABP_Fx_WayFinding_C) == 0x000008, "Wrong alignment on ABP_Fx_WayFinding_C");
static_assert(sizeof(ABP_Fx_WayFinding_C) == 0x0002E0, "Wrong size on ABP_Fx_WayFinding_C");
static_assert(offsetof(ABP_Fx_WayFinding_C, UberGraphFrame) == 0x0002B0, "Member 'ABP_Fx_WayFinding_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, NS_Fx_WayFinding) == 0x0002B8, "Member 'ABP_Fx_WayFinding_C::NS_Fx_WayFinding' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, Spline) == 0x0002C0, "Member 'ABP_Fx_WayFinding_C::Spline' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, Distance) == 0x0002C8, "Member 'ABP_Fx_WayFinding_C::Distance' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, MinFragmentsNum) == 0x0002CC, "Member 'ABP_Fx_WayFinding_C::MinFragmentsNum' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, Deactivating) == 0x0002D0, "Member 'ABP_Fx_WayFinding_C::Deactivating' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, DeactiveAlpha) == 0x0002D4, "Member 'ABP_Fx_WayFinding_C::DeactiveAlpha' has a wrong offset!");
static_assert(offsetof(ABP_Fx_WayFinding_C, DeactiveAlphaSpeed) == 0x0002D8, "Member 'ABP_Fx_WayFinding_C::DeactiveAlphaSpeed' has a wrong offset!");

}

