#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Input_Zhezhi

#include "Basic.hpp"

#include "BP_Input_Zhezhi_classes.hpp"
#include "BP_Input_Zhezhi_parameters.hpp"


namespace SDK
{

// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.攻击按下
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_Input_Zhezhi_C::攻击按下(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "攻击按下");

	Params::BP_Input_Zhezhi_C_攻击按下 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.技能1按下
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_Input_Zhezhi_C::技能1按下(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "技能1按下");

	Params::BP_Input_Zhezhi_C_技能1按下 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.攻击长按
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_Input_Zhezhi_C::攻击长按(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "攻击长按");

	Params::BP_Input_Zhezhi_C_攻击长按 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.技能1长按
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_Input_Zhezhi_C::技能1长按(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "技能1长按");

	Params::BP_Input_Zhezhi_C_技能1长按 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.飞鹤存在检测
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    存在                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Input_Zhezhi_C::飞鹤存在检测(bool* 存在)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "飞鹤存在检测");

	Params::BP_Input_Zhezhi_C_飞鹤存在检测 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (存在 != nullptr)
		*存在 = Parms.存在;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.大招按下
// (Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSInputCommand                   ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

struct FSInputCommand UBP_Input_Zhezhi_C::大招按下(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "大招按下");

	Params::BP_Input_Zhezhi_C_大招按下 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.飞鹤在空中
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    在空中                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Input_Zhezhi_C::飞鹤在空中(bool* 在空中)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "飞鹤在空中");

	Params::BP_Input_Zhezhi_C_飞鹤在空中 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (在空中 != nullptr)
		*在空中 = Parms.在空中;
}


// Function BP_Input_Zhezhi.BP_Input_Zhezhi_C.技能1抬起事件
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Input_Zhezhi_C::技能1抬起事件(float time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Input_Zhezhi_C", "技能1抬起事件");

	Params::BP_Input_Zhezhi_C_技能1抬起事件 Parms{};

	Parms.time = time;

	UObject::ProcessEvent(Func, &Parms);
}

}

