#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ME1DabuouMd00001_ControlMonster

#include "Basic.hpp"

#include "TsBaseCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ME1DabuouMd00001_ControlMonster.BP_ME1DabuouMd00001_ControlMonster_C
// 0x0000 (0x07B0 - 0x07B0)
class ABP_ME1DabuouMd00001_ControlMonster_C final : public ATsBaseCharacter_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ME1DabuouMd00001_ControlMonster_C">();
	}
	static class ABP_ME1DabuouMd00001_ControlMonster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ME1DabuouMd00001_ControlMonster_C>();
	}
};
static_assert(alignof(ABP_ME1DabuouMd00001_ControlMonster_C) == 0x000010, "Wrong alignment on ABP_ME1DabuouMd00001_ControlMonster_C");
static_assert(sizeof(ABP_ME1DabuouMd00001_ControlMonster_C) == 0x0007B0, "Wrong size on ABP_ME1DabuouMd00001_ControlMonster_C");

}

