#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vision_ME1Binlang

#include "Basic.hpp"

#include "BP_BaseVision_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Vision_ME1Binlang.BP_Vision_ME1Binlang_C
// 0x0000 (0x0790 - 0x0790)
class ABP_Vision_ME1Binlang_C final : public ABP_BaseVision_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Vision_ME1Binlang_C">();
	}
	static class ABP_Vision_ME1Binlang_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Vision_ME1Binlang_C>();
	}
};
static_assert(alignof(ABP_Vision_ME1Binlang_C) == 0x000010, "Wrong alignment on ABP_Vision_ME1Binlang_C");
static_assert(sizeof(ABP_Vision_ME1Binlang_C) == 0x000790, "Wrong size on ABP_Vision_ME1Binlang_C");

}

