#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_SceneBp

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_SceneBp.BPI_SceneBp_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_SceneBp_C final
{
public:
	void TickOutside();
	void Start();
	void Stop();
	void Pause();
	void Resume();

	void GetAoiRange(int32* ret) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_SceneBp_C">();
	}
	static class IBPI_SceneBp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_SceneBp_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_SceneBp_C) == 0x000001, "Wrong alignment on IBPI_SceneBp_C");
static_assert(sizeof(IBPI_SceneBp_C) == 0x000001, "Wrong size on IBPI_SceneBp_C");

}

