#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ECommonQteType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ECommonQteType.ECommonQteType
// NumValues: 0x0002
enum class ECommonQteType : uint8
{
	NewEnumerator0                           = 0,
	ECommonQteType_MAX                       = 1,
};

}

