#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EffectModelBillboard

#include "Basic.hpp"

#include "KuroGameplay_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass EffectModelBillboard.EffectModelBillboard_C
// 0x0000 (0x0070 - 0x0070)
class UEffectModelBillboard_C final : public UEffectModelBillboard
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EffectModelBillboard_C">();
	}
	static class UEffectModelBillboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectModelBillboard_C>();
	}
};
static_assert(alignof(UEffectModelBillboard_C) == 0x000008, "Wrong alignment on UEffectModelBillboard_C");
static_assert(sizeof(UEffectModelBillboard_C) == 0x000070, "Wrong size on UEffectModelBillboard_C");

}

