#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Bulante_Burst

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GA_Bulante_Burst.GA_Bulante_Burst_C.ExecuteUbergraph_GA_Bulante_Burst
// 0x08C0 (0x08C0 - 0x0000)
struct GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         ___object_Variable;                                // 0x0008(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0028)(ZeroConstructor)
	TArray<class AActor*>                         ___object_Variable_1;                              // 0x0040(0x0010)(ConstParm, ReferenceParm)
	TArray<class AActor*>                         ___object_Variable_2;                              // 0x0050(0x0010)(ConstParm, ReferenceParm)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc__________;                                // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0090(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_____GA______________;                     // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x00C8(0x0028)(ZeroConstructor)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x00F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________1;                              // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10A[0x6];                                      // 0x010A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_1; // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character_1;          // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc___________2;                              // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________3;                              // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc______________;                            // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________4;                              // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________1;                          // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________5;                              // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________6;                              // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________7;                              // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc__________SpeedRatio;                      // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________2;                          // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18D[0x3];                                      // 0x018D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue; // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x01A0(0x0028)(ZeroConstructor)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CC[0x4];                                      // 0x01CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc___________8;                              // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue_1;             // 0x01D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x01E8(0x0028)(ZeroConstructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue_1;             // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue_1;      // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x7];                                      // 0x0219(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0220(0x0028)(ZeroConstructor)
	class ATsBaseCharacter_C*                     CallFunc___________9;                              // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________3;                          // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_____GA_______________1;                   // 0x0258(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0268(0x0028)(ZeroConstructor)
	float                                         CallFunc__________SpeedRatio_1;                    // 0x0290(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_294[0x4];                                      // 0x0294(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_PlayMontageAndWait*        CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1; // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________10;                             // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_______________4;                          // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x02A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2AA[0x6];                                      // 0x02AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array;                            // 0x02B0(0x0010)(ConstParm, ReferenceParm)
	class ATsBaseCharacter_C*                     CallFunc___________11;                             // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc___________12;                             // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_K2_GetActorLocation_ReturnValue;        // 0x02D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x7];                                      // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVectorDouble_X;                      // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y;                      // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z;                      // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue;             // 0x0308(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_1;           // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_GetActorForwardVector_ReturnValue;      // 0x0318(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue;             // 0x0330(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue;       // 0x0348(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Add_VectorVector_ReturnValue;           // 0x0360(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array_1;                          // 0x0378(0x0010)(ConstParm, ReferenceParm)
	double                                        CallFunc_BreakVectorDouble_X_1;                    // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_1;                    // 0x0390(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_1;                    // 0x0398(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_2;           // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_3;           // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_1;          // 0x03B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue_1;           // 0x03C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_D_SphereTraceSingleForObjects_OutHit;     // 0x03D8(0x0094)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_D_SphereTraceSingleForObjects_ReturnValue; // 0x046C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_46D[0x3];                                      // 0x046D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________13;                             // 0x0470(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetHeightAboveGround_ReturnValue;         // 0x0478(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47C[0x4];                                      // 0x047C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0480(0x0028)(ZeroConstructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x04A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A9[0x7];                                      // 0x04A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc___________14;                             // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_K2_GetActorLocation_ReturnValue_1;      // 0x04B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x04D0(0x0028)(ZeroConstructor)
	double                                        CallFunc_BreakVectorDouble_X_2;                    // 0x04F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_2;                    // 0x0500(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_2;                    // 0x0508(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_4;           // 0x0510(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_5;           // 0x0518(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_GetActorForwardVector_ReturnValue_1;    // 0x0520(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue_1;     // 0x0538(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue_2;     // 0x0550(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Add_VectorVector_ReturnValue_1;         // 0x0568(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Add_VectorVector_ReturnValue_2;         // 0x0580(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_X_3;                    // 0x0598(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_3;                    // 0x05A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_3;                    // 0x05A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_X_4;                    // 0x05B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_4;                    // 0x05B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_4;                    // 0x05C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_6;           // 0x05C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_7;           // 0x05D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_8;           // 0x05D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_9;           // 0x05E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue_2;           // 0x05E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue_3;           // 0x0600(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_D_SphereTraceSingleForObjects_OutHit_1;   // 0x0618(0x0094)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_D_SphereTraceSingleForObjects_ReturnValue_1; // 0x06AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6AD[0x3];                                      // 0x06AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array_2;                          // 0x06B0(0x0010)(ConstParm, ReferenceParm)
	class ATsBaseCharacter_C*                     CallFunc___________15;                             // 0x06C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_K2_GetActorLocation_ReturnValue_2;      // 0x06C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x06E0(0x0028)(ZeroConstructor)
	double                                        CallFunc_BreakVectorDouble_X_5;                    // 0x0708(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_5;                    // 0x0710(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_5;                    // 0x0718(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_10;          // 0x0720(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_11;          // 0x0728(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_GetActorForwardVector_ReturnValue_2;    // 0x0730(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue_3;     // 0x0748(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Multiply_VectorFloat_ReturnValue_4;     // 0x0760(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Add_VectorVector_ReturnValue_3;         // 0x0778(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_D_Add_VectorVector_ReturnValue_4;         // 0x0790(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_X_6;                    // 0x07A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_6;                    // 0x07B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_6;                    // 0x07B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_X_7;                    // 0x07C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Y_7;                    // 0x07C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVectorDouble_Z_7;                    // 0x07D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_12;          // 0x07D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_13;          // 0x07E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_14;          // 0x07E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_D_Add_FloatFloat_ReturnValue_15;          // 0x07F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue_4;           // 0x07F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVectorDouble                          CallFunc_MakeVectorDouble_ReturnValue_5;           // 0x0810(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_D_SphereTraceSingleForObjects_OutHit_2;   // 0x0828(0x0094)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_D_SphereTraceSingleForObjects_ReturnValue_2; // 0x08BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst) == 0x000008, "Wrong alignment on GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst");
static_assert(sizeof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst) == 0x0008C0, "Wrong size on GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, EntryPoint) == 0x000000, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, ___object_Variable) == 0x000008, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::___object_Variable' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, ___object_Variable_1) == 0x000040, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::___object_Variable_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, ___object_Variable_2) == 0x000050, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::___object_Variable_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000060, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc__________) == 0x000068, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetDisplayName_ReturnValue) == 0x000070, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetObjectClass_ReturnValue) == 0x000080, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000088, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_1) == 0x000090, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_____GA______________) == 0x0000B8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_____GA______________' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_2) == 0x0000C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_Conv_NameToString_ReturnValue) == 0x0000F0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________1) == 0x000100, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_IsValid_ReturnValue) == 0x000108, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_Event_bWasCancelled) == 0x000109, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_Event_bWasCancelled' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetOwningActorFromActorInfo_ReturnValue) == 0x000110, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetOwningActorFromActorInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_DynamicCast_AsTs_Base_Character) == 0x000118, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_DynamicCast_AsTs_Base_Character' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_DynamicCast_bSuccess) == 0x000120, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetOwningActorFromActorInfo_ReturnValue_1) == 0x000128, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetOwningActorFromActorInfo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_DynamicCast_AsTs_Base_Character_1) == 0x000130, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_DynamicCast_AsTs_Base_Character_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_DynamicCast_bSuccess_1) == 0x000138, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________2) == 0x000140, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_IsValid_ReturnValue_1) == 0x000148, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________3) == 0x000150, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc______________) == 0x000158, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc______________' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________4) == 0x000160, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_______________1) == 0x000168, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_______________1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________5) == 0x000170, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________6) == 0x000178, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________7) == 0x000180, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc__________SpeedRatio) == 0x000188, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc__________SpeedRatio' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_______________2) == 0x00018C, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_______________2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue) == 0x000190, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_IsValid_ReturnValue_2) == 0x000198, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_3) == 0x0001A0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x0001C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________8) == 0x0001D0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________8' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetDisplayName_ReturnValue_1) == 0x0001D8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_4) == 0x0001E8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetObjectClass_ReturnValue_1) == 0x000210, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetObjectClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_EqualEqual_ClassClass_ReturnValue_1) == 0x000218, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_EqualEqual_ClassClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_5) == 0x000220, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________9) == 0x000248, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________9' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_______________3) == 0x000250, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_______________3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_____GA_______________1) == 0x000258, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_____GA_______________1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_6) == 0x000268, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc__________SpeedRatio_1) == 0x000290, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc__________SpeedRatio_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1) == 0x000298, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_CreatePlayMontageAndWaitProxy_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________10) == 0x0002A0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________10' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_______________4) == 0x0002A8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_______________4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_IsValid_ReturnValue_3) == 0x0002A9, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_MakeArray_Array) == 0x0002B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________11) == 0x0002C0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________11' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________12) == 0x0002C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________12' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_K2_GetActorLocation_ReturnValue) == 0x0002D0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_IsValid_ReturnValue_4) == 0x0002E8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X) == 0x0002F0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y) == 0x0002F8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z) == 0x000300, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue) == 0x000308, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_1) == 0x000310, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_GetActorForwardVector_ReturnValue) == 0x000318, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue) == 0x000330, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Multiply_VectorFloat_ReturnValue) == 0x000348, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_VectorVector_ReturnValue) == 0x000360, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_MakeArray_Array_1) == 0x000378, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_1) == 0x000388, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_1) == 0x000390, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_1) == 0x000398, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_2) == 0x0003A0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_3) == 0x0003A8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_Conv_NameToString_ReturnValue_1) == 0x0003B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_Conv_NameToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue_1) == 0x0003C0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_OutHit) == 0x0003D8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_ReturnValue) == 0x00046C, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________13) == 0x000470, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________13' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GetHeightAboveGround_ReturnValue) == 0x000478, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GetHeightAboveGround_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_7) == 0x000480, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0004A8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________14) == 0x0004B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________14' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_K2_GetActorLocation_ReturnValue_1) == 0x0004B8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_8) == 0x0004D0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_2) == 0x0004F8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_2) == 0x000500, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_2) == 0x000508, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_4) == 0x000510, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_5) == 0x000518, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_GetActorForwardVector_ReturnValue_1) == 0x000520, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_GetActorForwardVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Multiply_VectorFloat_ReturnValue_1) == 0x000538, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Multiply_VectorFloat_ReturnValue_2) == 0x000550, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Multiply_VectorFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_VectorVector_ReturnValue_1) == 0x000568, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_VectorVector_ReturnValue_2) == 0x000580, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_VectorVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_3) == 0x000598, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_3) == 0x0005A0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_3) == 0x0005A8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_4) == 0x0005B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_4) == 0x0005B8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_4) == 0x0005C0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_6) == 0x0005C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_7) == 0x0005D0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_8) == 0x0005D8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_9) == 0x0005E0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue_2) == 0x0005E8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue_3) == 0x000600, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_OutHit_1) == 0x000618, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_OutHit_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_ReturnValue_1) == 0x0006AC, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_MakeArray_Array_2) == 0x0006B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc___________15) == 0x0006C0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc___________15' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_K2_GetActorLocation_ReturnValue_2) == 0x0006C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, K2Node_CreateDelegate_OutputDelegate_9) == 0x0006E0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_5) == 0x000708, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_5) == 0x000710, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_5) == 0x000718, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_10) == 0x000720, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_11) == 0x000728, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_GetActorForwardVector_ReturnValue_2) == 0x000730, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_GetActorForwardVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Multiply_VectorFloat_ReturnValue_3) == 0x000748, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Multiply_VectorFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Multiply_VectorFloat_ReturnValue_4) == 0x000760, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Multiply_VectorFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_VectorVector_ReturnValue_3) == 0x000778, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_VectorVector_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_VectorVector_ReturnValue_4) == 0x000790, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_VectorVector_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_6) == 0x0007A8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_6) == 0x0007B0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_6) == 0x0007B8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_6' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_X_7) == 0x0007C0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_X_7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Y_7) == 0x0007C8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Y_7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_BreakVectorDouble_Z_7) == 0x0007D0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_BreakVectorDouble_Z_7' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_12) == 0x0007D8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_13) == 0x0007E0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_14) == 0x0007E8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_Add_FloatFloat_ReturnValue_15) == 0x0007F0, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_Add_FloatFloat_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue_4) == 0x0007F8, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_MakeVectorDouble_ReturnValue_5) == 0x000810, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_MakeVectorDouble_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_OutHit_2) == 0x000828, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_OutHit_2' has a wrong offset!");
static_assert(offsetof(GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst, CallFunc_D_SphereTraceSingleForObjects_ReturnValue_2) == 0x0008BC, "Member 'GA_Bulante_Burst_C_ExecuteUbergraph_GA_Bulante_Burst::CallFunc_D_SphereTraceSingleForObjects_ReturnValue_2' has a wrong offset!");

// Function GA_Bulante_Burst.GA_Bulante_Burst_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_Bulante_Burst_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GA_Bulante_Burst_C_K2_OnEndAbility) == 0x000001, "Wrong alignment on GA_Bulante_Burst_C_K2_OnEndAbility");
static_assert(sizeof(GA_Bulante_Burst_C_K2_OnEndAbility) == 0x000001, "Wrong size on GA_Bulante_Burst_C_K2_OnEndAbility");
static_assert(offsetof(GA_Bulante_Burst_C_K2_OnEndAbility, bWasCancelled) == 0x000000, "Member 'GA_Bulante_Burst_C_K2_OnEndAbility::bWasCancelled' has a wrong offset!");

}

