#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Bulante_ExitSkill

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_Bulante_ExitSkill.GA_Bulante_ExitSkill_C.ExecuteUbergraph_GA_Bulante_ExitSkill
// 0x0030 (0x0030 - 0x0000)
struct GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     CallFunc__________;                                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc___________1;                              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     CallFunc_GetGoBattleActor_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill) == 0x000008, "Wrong alignment on GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill");
static_assert(sizeof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill) == 0x000030, "Wrong size on GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill");
static_assert(offsetof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill, EntryPoint) == 0x000000, "Member 'GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill::EntryPoint' has a wrong offset!");
static_assert(offsetof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill, CallFunc__________) == 0x000008, "Member 'GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill::CallFunc__________' has a wrong offset!");
static_assert(offsetof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill, CallFunc___________1) == 0x000010, "Member 'GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill::CallFunc___________1' has a wrong offset!");
static_assert(offsetof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill, CallFunc_GetGoBattleActor_ReturnValue) == 0x000018, "Member 'GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill::CallFunc_GetGoBattleActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill, CallFunc_Conv_IntToString_ReturnValue) == 0x000020, "Member 'GA_Bulante_ExitSkill_C_ExecuteUbergraph_GA_Bulante_ExitSkill::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");

}

