#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Destroy_Bianshen_BinLangBing_Vision

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Destroy_Bianshen_BinLangBing_Vision.GA_Destroy_Bianshen_BinLangBing_Vision_C
// 0x0038 (0x0590 - 0x0558)
class UGA_Destroy_Bianshen_BinLangBing_Vision_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Destroy_Bianshen_BinLangBing_Vision_C; // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         召唤者ID;                                          // 0x0560(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_564[0x4];                                      // 0x0564(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATsBaseCharacter_C*                     召唤者;                                            // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BaseVision_C*                       幻象BP;                                            // 0x0570(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UObject*                                变身结束_粒子特效;                                 // 0x0578(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                变身结束_材质特效;                                 // 0x0580(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          主动结束;                                          // 0x0588(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          已结束;                                            // 0x0589(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_58A[0x2];                                      // 0x058A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         材质Handle;                                        // 0x058C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Destroy_Bianshen_BinLangBing_Vision(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnFinish_F68DBCAE414E6616B20B1D922F40AD50();
	void EventReceived_18B59F5945020DB23C42FD88EA87080F(const struct FGameplayEventData& Payload);
	void EventReceived_18B59F5945020DB23C42FD88CA99C183(const struct FGameplayEventData& Payload);
	void Added_21071CB943CD992BF8EFD6A3C8F7021E(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A354A18047(const struct FGameplayTag& Tag);
	void EventReceived_18B59F5945020DB23C42FD888414D564(const struct FGameplayEventData& Payload);
	void OnCompleted_5D118C384AE61F1C80292E81128F6642();
	void OnBlendOut_5D118C384AE61F1C80292E81128F6642();
	void OnInterrupted_5D118C384AE61F1C80292E81128F6642();
	void OnCancelled_5D118C384AE61F1C80292E81128F6642();
	void OnTick_5D118C384AE61F1C80292E81128F6642();
	void 显示玩家模型();
	void 变身结束_碰撞关系处理();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Destroy_Bianshen_BinLangBing_Vision_C">();
	}
	static class UGA_Destroy_Bianshen_BinLangBing_Vision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Destroy_Bianshen_BinLangBing_Vision_C>();
	}
};
static_assert(alignof(UGA_Destroy_Bianshen_BinLangBing_Vision_C) == 0x000008, "Wrong alignment on UGA_Destroy_Bianshen_BinLangBing_Vision_C");
static_assert(sizeof(UGA_Destroy_Bianshen_BinLangBing_Vision_C) == 0x000590, "Wrong size on UGA_Destroy_Bianshen_BinLangBing_Vision_C");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, UberGraphFrame_GA_Destroy_Bianshen_BinLangBing_Vision_C) == 0x000558, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::UberGraphFrame_GA_Destroy_Bianshen_BinLangBing_Vision_C' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 召唤者ID) == 0x000560, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::召唤者ID' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 召唤者) == 0x000568, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::召唤者' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 幻象BP) == 0x000570, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::幻象BP' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 变身结束_粒子特效) == 0x000578, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::变身结束_粒子特效' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 变身结束_材质特效) == 0x000580, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::变身结束_材质特效' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 主动结束) == 0x000588, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::主动结束' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 已结束) == 0x000589, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::已结束' has a wrong offset!");
static_assert(offsetof(UGA_Destroy_Bianshen_BinLangBing_Vision_C, 材质Handle) == 0x00058C, "Member 'UGA_Destroy_Bianshen_BinLangBing_Vision_C::材质Handle' has a wrong offset!");

}

