#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Line_YinlinInstance

#include "Basic.hpp"

#include "GA_Line_YinlinInstance_classes.hpp"
#include "GA_Line_YinlinInstance_parameters.hpp"


namespace SDK
{

// Function GA_Line_YinlinInstance.GA_Line_YinlinInstance_C.ExecuteUbergraph_GA_Line_YinlinInstance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Line_YinlinInstance_C::ExecuteUbergraph_GA_Line_YinlinInstance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Line_YinlinInstance_C", "ExecuteUbergraph_GA_Line_YinlinInstance");

	Params::GA_Line_YinlinInstance_C_ExecuteUbergraph_GA_Line_YinlinInstance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Line_YinlinInstance.GA_Line_YinlinInstance_C.给怪物添加对应下标buff
// (BlueprintCallable, BlueprintEvent)

void UGA_Line_YinlinInstance_C::给怪物添加对应下标buff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Line_YinlinInstance_C", "给怪物添加对应下标buff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Line_YinlinInstance.GA_Line_YinlinInstance_C.检测自身tag获取下标
// (BlueprintCallable, BlueprintEvent)

void UGA_Line_YinlinInstance_C::检测自身tag获取下标()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Line_YinlinInstance_C", "检测自身tag获取下标");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Line_YinlinInstance.GA_Line_YinlinInstance_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Line_YinlinInstance_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Line_YinlinInstance_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

