#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ME_LFZ_Attack02

#include "Basic.hpp"

#include "GA_ME_LFZ_Attack02_classes.hpp"
#include "GA_ME_LFZ_Attack02_parameters.hpp"


namespace SDK
{

// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.ExecuteUbergraph_GA_ME_LFZ_Attack02
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_ME_LFZ_Attack02_C::ExecuteUbergraph_GA_ME_LFZ_Attack02(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "ExecuteUbergraph_GA_ME_LFZ_Attack02");

	Params::GA_ME_LFZ_Attack02_C_ExecuteUbergraph_GA_ME_LFZ_Attack02 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.OnCompleted_5D118C384AE61F1C80292E81B5E19EE7
// (BlueprintCallable, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::OnCompleted_5D118C384AE61F1C80292E81B5E19EE7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "OnCompleted_5D118C384AE61F1C80292E81B5E19EE7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.OnBlendOut_5D118C384AE61F1C80292E81B5E19EE7
// (BlueprintCallable, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::OnBlendOut_5D118C384AE61F1C80292E81B5E19EE7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "OnBlendOut_5D118C384AE61F1C80292E81B5E19EE7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.OnInterrupted_5D118C384AE61F1C80292E81B5E19EE7
// (BlueprintCallable, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::OnInterrupted_5D118C384AE61F1C80292E81B5E19EE7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "OnInterrupted_5D118C384AE61F1C80292E81B5E19EE7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.OnCancelled_5D118C384AE61F1C80292E81B5E19EE7
// (BlueprintCallable, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::OnCancelled_5D118C384AE61F1C80292E81B5E19EE7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "OnCancelled_5D118C384AE61F1C80292E81B5E19EE7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.OnTick_5D118C384AE61F1C80292E81B5E19EE7
// (BlueprintCallable, BlueprintEvent)

void UGA_ME_LFZ_Attack02_C::OnTick_5D118C384AE61F1C80292E81B5E19EE7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "OnTick_5D118C384AE61F1C80292E81B5E19EE7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ME_LFZ_Attack02.GA_ME_LFZ_Attack02_C.EventReceived_18B59F5945020DB23C42FD88E52B7545
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_ME_LFZ_Attack02_C::EventReceived_18B59F5945020DB23C42FD88E52B7545(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ME_LFZ_Attack02_C", "EventReceived_18B59F5945020DB23C42FD88E52B7545");

	Params::GA_ME_LFZ_Attack02_C_EventReceived_18B59F5945020DB23C42FD88E52B7545 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}

}

