#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Skill03

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Skill03.GA_Skill03_C
// 0x0008 (0x0560 - 0x0558)
class UGA_Skill03_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Skill03_C;                       // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Skill03(int32 EntryPoint);
	void K2_ActivateAbility();
	void EventReceived_8EC676D941E5C7FD48F4F7BAB15C4824(const struct FGameplayEventData& Payload);
	void OnCompleted_5D118C384AE61F1C80292E81AD868444();
	void OnBlendOut_5D118C384AE61F1C80292E81AD868444();
	void OnInterrupted_5D118C384AE61F1C80292E81AD868444();
	void OnCancelled_5D118C384AE61F1C80292E81AD868444();
	void OnTick_5D118C384AE61F1C80292E81AD868444();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Skill03_C">();
	}
	static class UGA_Skill03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Skill03_C>();
	}
};
static_assert(alignof(UGA_Skill03_C) == 0x000008, "Wrong alignment on UGA_Skill03_C");
static_assert(sizeof(UGA_Skill03_C) == 0x000560, "Wrong size on UGA_Skill03_C");
static_assert(offsetof(UGA_Skill03_C, UberGraphFrame_GA_Skill03_C) == 0x000558, "Member 'UGA_Skill03_C::UberGraphFrame_GA_Skill03_C' has a wrong offset!");

}

