#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroPushSdk

#include "Basic.hpp"

#include "KuroPushSdk_classes.hpp"
#include "KuroPushSdk_parameters.hpp"


namespace SDK
{

// Function KuroPushSdk.KuroPushSdkStaticLibrary.AreNotificationEnable
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::AreNotificationEnable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "AreNotificationEnable");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.BindAlias
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    alias                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    sn                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::BindAlias(const class FString& alias, const class FString& sn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "BindAlias");

	Params::KuroPushSdkStaticLibrary_BindAlias Parms{};

	Parms.alias = std::move(alias);
	Parms.sn = std::move(sn);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.CheckManifest
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::CheckManifest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "CheckManifest");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.ClearNotificationForNotificationBar
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::ClearNotificationForNotificationBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "ClearNotificationForNotificationBar");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.Destroy
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::Destroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "Destroy");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.GetClientId
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UKuroPushSdkStaticLibrary::GetClientId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "GetClientId");

	Params::KuroPushSdkStaticLibrary_GetClientId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.GetPushObject
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UKuroPushObject*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UKuroPushObject* UKuroPushSdkStaticLibrary::GetPushObject()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "GetPushObject");

	Params::KuroPushSdkStaticLibrary_GetPushObject Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.GetStatus
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UKuroPushSdkStaticLibrary::GetStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "GetStatus");

	Params::KuroPushSdkStaticLibrary_GetStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.GetVersion
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UKuroPushSdkStaticLibrary::GetVersion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "GetVersion");

	Params::KuroPushSdkStaticLibrary_GetVersion Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.Init
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "Init");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.IsPushTurnOn
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroPushSdkStaticLibrary::IsPushTurnOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "IsPushTurnOn");

	Params::KuroPushSdkStaticLibrary_IsPushTurnOn Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.OpenNotification
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::OpenNotification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "OpenNotification");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.PushLocalNotification
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    title                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    body                                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    exData                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::PushLocalNotification(const class FString& title, const class FString& body, const class FString& exData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "PushLocalNotification");

	Params::KuroPushSdkStaticLibrary_PushLocalNotification Parms{};

	Parms.title = std::move(title);
	Parms.body = std::move(body);
	Parms.exData = std::move(exData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.RegistRemoteNotification
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::RegistRemoteNotification()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "RegistRemoteNotification");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.ResetBudge
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::ResetBudge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "ResetBudge");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.Resume
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "Resume");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SendFeedBackMessage
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    actionId                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    taskId                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    msgId                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SendFeedBackMessage(const class FString& actionId, const class FString& taskId, const class FString& msgId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SendFeedBackMessage");

	Params::KuroPushSdkStaticLibrary_SendFeedBackMessage Parms{};

	Parms.actionId = std::move(actionId);
	Parms.taskId = std::move(taskId);
	Parms.msgId = std::move(msgId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetApplicationGroupIdentify
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    identify                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetApplicationGroupIdentify(const class FString& identify)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetApplicationGroupIdentify");

	Params::KuroPushSdkStaticLibrary_SetApplicationGroupIdentify Parms{};

	Parms.identify = std::move(identify);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetBudge
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    budge                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetBudge(const class FString& budge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetBudge");

	Params::KuroPushSdkStaticLibrary_SetBudge Parms{};

	Parms.budge = std::move(budge);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetChannel
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    channelId                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetChannel(const class FString& channelId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetChannel");

	Params::KuroPushSdkStaticLibrary_SetChannel Parms{};

	Parms.channelId = std::move(channelId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetDebug
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::SetDebug()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetDebug");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetLocalChannelId
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FString*                          channelId                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetLocalChannelId(class FString* channelId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetLocalChannelId");

	Params::KuroPushSdkStaticLibrary_SetLocalChannelId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (channelId != nullptr)
		*channelId = std::move(Parms.channelId);
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetLocalChannelIdAndName
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FString*                          channelId                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          channelName                                            (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetLocalChannelIdAndName(class FString* channelId, class FString* channelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetLocalChannelIdAndName");

	Params::KuroPushSdkStaticLibrary_SetLocalChannelIdAndName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (channelId != nullptr)
		*channelId = std::move(Parms.channelId);

	if (channelName != nullptr)
		*channelName = std::move(Parms.channelName);
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetLocalSetNotificationIcon
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FString*                          smallIcon                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          largeIcon                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetLocalSetNotificationIcon(class FString* smallIcon, class FString* largeIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetLocalSetNotificationIcon");

	Params::KuroPushSdkStaticLibrary_SetLocalSetNotificationIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (smallIcon != nullptr)
		*smallIcon = std::move(Parms.smallIcon);

	if (largeIcon != nullptr)
		*largeIcon = std::move(Parms.largeIcon);
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetLocationEnable
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    isEnable                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    isVerify                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetLocationEnable(bool isEnable, bool isVerify)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetLocationEnable");

	Params::KuroPushSdkStaticLibrary_SetLocationEnable Parms{};

	Parms.isEnable = isEnable;
	Parms.isVerify = isVerify;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetNotificationIcon
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class FString*                          smallIcon                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          largeIcon                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetNotificationIcon(class FString* smallIcon, class FString* largeIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetNotificationIcon");

	Params::KuroPushSdkStaticLibrary_SetNotificationIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (smallIcon != nullptr)
		*smallIcon = std::move(Parms.smallIcon);

	if (largeIcon != nullptr)
		*largeIcon = std::move(Parms.largeIcon);
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetPushMode
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    turnOn                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetPushMode(bool turnOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetPushMode");

	Params::KuroPushSdkStaticLibrary_SetPushMode Parms{};

	Parms.turnOn = turnOn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetRunInBackGround
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    state                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::SetRunInBackGround(bool state)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetRunInBackGround");

	Params::KuroPushSdkStaticLibrary_SetRunInBackGround Parms{};

	Parms.state = state;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.SetTag
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    tags                                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    sn                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroPushSdkStaticLibrary::SetTag(const class FString& tags, const class FString& sn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "SetTag");

	Params::KuroPushSdkStaticLibrary_SetTag Parms{};

	Parms.tags = std::move(tags);
	Parms.sn = std::move(sn);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.StartPushSdk
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    appId                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    appKey                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    appSecret                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::StartPushSdk(const class FString& appId, const class FString& appKey, const class FString& appSecret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "StartPushSdk");

	Params::KuroPushSdkStaticLibrary_StartPushSdk Parms{};

	Parms.appId = std::move(appId);
	Parms.appKey = std::move(appKey);
	Parms.appSecret = std::move(appSecret);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.TurnOffPush
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::TurnOffPush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "TurnOffPush");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.TurnOnPush
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::TurnOnPush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "TurnOnPush");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.UnBindAlias
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    alias                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    sn                                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    isSelf                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroPushSdkStaticLibrary::UnBindAlias(const class FString& alias, const class FString& sn, bool isSelf)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "UnBindAlias");

	Params::KuroPushSdkStaticLibrary_UnBindAlias Parms{};

	Parms.alias = std::move(alias);
	Parms.sn = std::move(sn);
	Parms.isSelf = isSelf;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroPushSdk.KuroPushSdkStaticLibrary.VoipRegistration
// (Final, Native, Static, Public, BlueprintCallable)

void UKuroPushSdkStaticLibrary::VoipRegistration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroPushSdkStaticLibrary", "VoipRegistration");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

