#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroComponent

#include "Basic.hpp"

#include "KuroComponent_classes.hpp"
#include "KuroComponent_parameters.hpp"


namespace SDK
{

// Function KuroComponent.KuroAnimPerfTestComponent.DestroySkeletalMeshActors
// (Final, Native, Public, BlueprintCallable)

void UKuroAnimPerfTestComponent::DestroySkeletalMeshActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroAnimPerfTestComponent", "DestroySkeletalMeshActors");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroAnimPerfTestComponent.GenerateSkeletalMeshActors
// (Final, Native, Public, BlueprintCallable)

void UKuroAnimPerfTestComponent::GenerateSkeletalMeshActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroAnimPerfTestComponent", "GenerateSkeletalMeshActors");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroChainComponent.InitChain
// (Native, Protected, BlueprintCallable)

void UKuroChainComponent::InitChain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroChainComponent", "InitChain");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.AddModelLocation
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVector&                   Offset                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroCharacterAnimationComponent::AddModelLocation(const struct FVector& Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "AddModelLocation");

	Params::KuroCharacterAnimationComponent_AddModelLocation Parms{};

	Parms.Offset = std::move(Offset);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.AddModelQuat
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FQuat&                     Quat                                                   (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// bool                                    LockCenter                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroCharacterAnimationComponent::AddModelQuat(const struct FQuat& Quat, bool LockCenter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "AddModelQuat");

	Params::KuroCharacterAnimationComponent_AddModelQuat Parms{};

	Parms.Quat = std::move(Quat);
	Parms.LockCenter = LockCenter;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.D_GetTransformOffsetInWorld
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FTransformDouble&          Child                                                  (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// const struct FTransformDouble&          Parent                                                 (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

void UKuroCharacterAnimationComponent::D_GetTransformOffsetInWorld(const struct FTransformDouble& Child, const struct FTransformDouble& Parent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "D_GetTransformOffsetInWorld");

	Params::KuroCharacterAnimationComponent_D_GetTransformOffsetInWorld Parms{};

	Parms.Child = std::move(Child);
	Parms.Parent = std::move(Parent);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.GetTransformOffsetInWorld
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FTransform&                Child                                                  (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// const struct FTransform&                Parent                                                 (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

void UKuroCharacterAnimationComponent::GetTransformOffsetInWorld(const struct FTransform& Child, const struct FTransform& Parent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "GetTransformOffsetInWorld");

	Params::KuroCharacterAnimationComponent_GetTransformOffsetInWorld Parms{};

	Parms.Child = std::move(Child);
	Parms.Parent = std::move(Parent);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.ResetModelLocation
// (Final, Native, Public, BlueprintCallable)

void UKuroCharacterAnimationComponent::ResetModelLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "ResetModelLocation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.ResetModelQuat
// (Final, Native, Public, BlueprintCallable)

void UKuroCharacterAnimationComponent::ResetModelQuat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "ResetModelQuat");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroCharacterAnimationComponent.StopModelBuffer
// (Final, Native, Public, BlueprintCallable)

void UKuroCharacterAnimationComponent::StopModelBuffer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCharacterAnimationComponent", "StopModelBuffer");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroRegionDetectComponent.GetRegionEvent
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    RegionName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UKuroRegionEventBinder*           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UKuroRegionEventBinder* UKuroRegionDetectComponent::GetRegionEvent(const class FString& RegionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "GetRegionEvent");

	Params::KuroRegionDetectComponent_GetRegionEvent Parms{};

	Parms.RegionName = std::move(RegionName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroRegionDetectComponent.ResetEventTargets
// (Final, Native, Public, BlueprintCallable)

void UKuroRegionDetectComponent::ResetEventTargets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "ResetEventTargets");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroRegionDetectComponent.SetDebugMode
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              IsOpen                                                 (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroRegionDetectComponent::SetDebugMode(const bool IsOpen)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "SetDebugMode");

	Params::KuroRegionDetectComponent_SetDebugMode Parms{};

	Parms.IsOpen = IsOpen;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroRegionDetectComponent.SetEventTarget
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           DetectTarget                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroRegionDetectComponent::SetEventTarget(class AActor* DetectTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "SetEventTarget");

	Params::KuroRegionDetectComponent_SetEventTarget Parms{};

	Parms.DetectTarget = DetectTarget;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroRegionDetectComponent.SetEventTargets
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const TArray<class AActor*>&            DetectTargets                                          (Parm, ZeroConstructor, NativeAccessSpecifierPublic)

void UKuroRegionDetectComponent::SetEventTargets(const TArray<class AActor*>& DetectTargets)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "SetEventTargets");

	Params::KuroRegionDetectComponent_SetEventTargets Parms{};

	Parms.DetectTargets = std::move(DetectTargets);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroRegionDetectComponent.Detect
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FVectorDouble&             Point                                                  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    RegionName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroRegionDetectComponent::Detect(const struct FVectorDouble& Point, const class FString& RegionName) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroRegionDetectComponent", "Detect");

	Params::KuroRegionDetectComponent_Detect Parms{};

	Parms.Point = std::move(Point);
	Parms.RegionName = std::move(RegionName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemGuidePathComponent.StartTick
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor&              Normal                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FLinearColor&              ChangeCoefficient                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FLinearColor&              Finish                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ParameterName                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   TotalCountDown                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   CurCountDown                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemGuidePathComponent::StartTick(const struct FLinearColor& Normal, const struct FLinearColor& ChangeCoefficient, const struct FLinearColor& Finish, class FName ParameterName, float TotalCountDown, float CurCountDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemGuidePathComponent", "StartTick");

	Params::KuroSceneItemGuidePathComponent_StartTick Parms{};

	Parms.Normal = std::move(Normal);
	Parms.ChangeCoefficient = std::move(ChangeCoefficient);
	Parms.Finish = std::move(Finish);
	Parms.ParameterName = ParameterName;
	Parms.TotalCountDown = TotalCountDown;
	Parms.CurCountDown = CurCountDown;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.FindTimeByValueIn01Curve
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class UCurveFloat*                Curve                                                  (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             TargetValue                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float*                                  ResultTime                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   MaxSearchDepth                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             Tolerance                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::FindTimeByValueIn01Curve(const class UCurveFloat* Curve, const float TargetValue, float* ResultTime, int32 MaxSearchDepth, const float Tolerance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroSceneItemMoveComponent", "FindTimeByValueIn01Curve");

	Params::KuroSceneItemMoveComponent_FindTimeByValueIn01Curve Parms{};

	Parms.Curve = Curve;
	Parms.TargetValue = TargetValue;
	Parms.MaxSearchDepth = MaxSearchDepth;
	Parms.Tolerance = Tolerance;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (ResultTime != nullptr)
		*ResultTime = Parms.ResultTime;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.AddMoveTarget
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVectorDouble&             Loc                                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   MoveTime                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   WaitTime                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   MaxSpeed                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Acceleration                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::AddMoveTarget(const struct FVectorDouble& Loc, float MoveTime, float WaitTime, float MaxSpeed, float Acceleration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "AddMoveTarget");

	Params::KuroSceneItemMoveComponent_AddMoveTarget Parms{};

	Parms.Loc = std::move(Loc);
	Parms.MoveTime = MoveTime;
	Parms.WaitTime = WaitTime;
	Parms.MaxSpeed = MaxSpeed;
	Parms.Acceleration = Acceleration;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.AddRotationStep
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FRotator&                  BeginRotation                                          (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// const struct FRotator&                  EndRotation                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   TimeSec                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   CdSec                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UCurveFloat*                      RotateCurve                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::AddRotationStep(const struct FRotator& BeginRotation, const struct FRotator& EndRotation, float TimeSec, float CdSec, class UCurveFloat* RotateCurve)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "AddRotationStep");

	Params::KuroSceneItemMoveComponent_AddRotationStep Parms{};

	Parms.BeginRotation = std::move(BeginRotation);
	Parms.EndRotation = std::move(EndRotation);
	Parms.TimeSec = TimeSec;
	Parms.CdSec = CdSec;
	Parms.RotateCurve = RotateCurve;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.GetNextMoveTarget
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct FVectorDouble*                   NextTarget                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVectorDouble*                   CurrentVelocity                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::GetNextMoveTarget(struct FVectorDouble* NextTarget, struct FVectorDouble* CurrentVelocity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "GetNextMoveTarget");

	Params::KuroSceneItemMoveComponent_GetNextMoveTarget Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (NextTarget != nullptr)
		*NextTarget = std::move(Parms.NextTarget);

	if (CurrentVelocity != nullptr)
		*CurrentVelocity = std::move(Parms.CurrentVelocity);

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.InitRotationData
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           TargetActor                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    IsLoop                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::InitRotationData(class AActor* TargetActor, bool IsLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "InitRotationData");

	Params::KuroSceneItemMoveComponent_InitRotationData Parms{};

	Parms.TargetActor = TargetActor;
	Parms.IsLoop = IsLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.Kuro_SetGravityDirect
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVector&                   InGravityDirect                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::Kuro_SetGravityDirect(const struct FVector& InGravityDirect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "Kuro_SetGravityDirect");

	Params::KuroSceneItemMoveComponent_Kuro_SetGravityDirect Parms{};

	Parms.InGravityDirect = std::move(InGravityDirect);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.SetEnableDebugForMove
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    Enable                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::SetEnableDebugForMove(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "SetEnableDebugForMove");

	Params::KuroSceneItemMoveComponent_SetEnableDebugForMove Parms{};

	Parms.Enable = Enable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.SetMaxDeltaDegreePerSecondForUpdatingLookAt
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const float                             MaxDegreePerSecond                                     (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::SetMaxDeltaDegreePerSecondForUpdatingLookAt(const float MaxDegreePerSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "SetMaxDeltaDegreePerSecondForUpdatingLookAt");

	Params::KuroSceneItemMoveComponent_SetMaxDeltaDegreePerSecondForUpdatingLookAt Parms{};

	Parms.MaxDegreePerSecond = MaxDegreePerSecond;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.SetTickingMoveEnable
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnabled                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::SetTickingMoveEnable(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "SetTickingMoveEnable");

	Params::KuroSceneItemMoveComponent_SetTickingMoveEnable Parms{};

	Parms.bEnabled = bEnabled;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.SetTickingRotateEnable
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnabled                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::SetTickingRotateEnable(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "SetTickingRotateEnable");

	Params::KuroSceneItemMoveComponent_SetTickingRotateEnable Parms{};

	Parms.bEnabled = bEnabled;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.StartMoveWithSplineAtConstantTime
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class USplineComponent*                 SplineComponent                                        (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    Repeat                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    Cycle                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    KeepLookAt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             TimeSec                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UCurveFloat*                      TimeDisCurve                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             StartTimeOffset                                        (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   StartDis                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   EndDis                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::StartMoveWithSplineAtConstantTime(class USplineComponent* SplineComponent, bool Repeat, bool Cycle, bool KeepLookAt, const float TimeSec, class UCurveFloat* TimeDisCurve, const float StartTimeOffset, float StartDis, float EndDis)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "StartMoveWithSplineAtConstantTime");

	Params::KuroSceneItemMoveComponent_StartMoveWithSplineAtConstantTime Parms{};

	Parms.SplineComponent = SplineComponent;
	Parms.Repeat = Repeat;
	Parms.Cycle = Cycle;
	Parms.KeepLookAt = KeepLookAt;
	Parms.TimeSec = TimeSec;
	Parms.TimeDisCurve = TimeDisCurve;
	Parms.StartTimeOffset = StartTimeOffset;
	Parms.StartDis = StartDis;
	Parms.EndDis = EndDis;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.StartMoveWithSplineAtDynamicSpeed
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class USplineComponent*                 SplineComponent                                        (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const int32                             MaxMoveTimes                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    Cycle                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    KeepLookAt                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             InitSpeed                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             Acceleration                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             TargetSpeed                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             StartDis                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             EndDis                                                 (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::StartMoveWithSplineAtDynamicSpeed(class USplineComponent* SplineComponent, const int32 MaxMoveTimes, bool Cycle, bool KeepLookAt, const float InitSpeed, const float Acceleration, const float TargetSpeed, const float StartDis, const float EndDis)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "StartMoveWithSplineAtDynamicSpeed");

	Params::KuroSceneItemMoveComponent_StartMoveWithSplineAtDynamicSpeed Parms{};

	Parms.SplineComponent = SplineComponent;
	Parms.MaxMoveTimes = MaxMoveTimes;
	Parms.Cycle = Cycle;
	Parms.KeepLookAt = KeepLookAt;
	Parms.InitSpeed = InitSpeed;
	Parms.Acceleration = Acceleration;
	Parms.TargetSpeed = TargetSpeed;
	Parms.StartDis = StartDis;
	Parms.EndDis = EndDis;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.StartRotate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::StartRotate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "StartRotate");

	Params::KuroSceneItemMoveComponent_StartRotate Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.StopAllMove
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    BroadcastStopCallback                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    BroadcastIndexCallback                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroSceneItemMoveComponent::StopAllMove(bool BroadcastStopCallback, bool BroadcastIndexCallback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "StopAllMove");

	Params::KuroSceneItemMoveComponent_StopAllMove Parms{};

	Parms.BroadcastStopCallback = BroadcastStopCallback;
	Parms.BroadcastIndexCallback = BroadcastIndexCallback;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroComponent.KuroSceneItemMoveComponent.StopRotate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// EKuroSceneItemStopRotateMethod          StopMethod                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::StopRotate(EKuroSceneItemStopRotateMethod StopMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "StopRotate");

	Params::KuroSceneItemMoveComponent_StopRotate Parms{};

	Parms.StopMethod = StopMethod;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.UpdateDynamicSpeedSplineMoveParams
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const float                             CurrentSpeed                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             Acceleration                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const float                             TargetSpeed                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::UpdateDynamicSpeedSplineMoveParams(const float CurrentSpeed, const float Acceleration, const float TargetSpeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "UpdateDynamicSpeedSplineMoveParams");

	Params::KuroSceneItemMoveComponent_UpdateDynamicSpeedSplineMoveParams Parms{};

	Parms.CurrentSpeed = CurrentSpeed;
	Parms.Acceleration = Acceleration;
	Parms.TargetSpeed = TargetSpeed;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.UpdateSplineMoveDistance
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const float                             NewDistanceAloneSpline                                 (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::UpdateSplineMoveDistance(const float NewDistanceAloneSpline)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "UpdateSplineMoveDistance");

	Params::KuroSceneItemMoveComponent_UpdateSplineMoveDistance Parms{};

	Parms.NewDistanceAloneSpline = NewDistanceAloneSpline;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.UpdateSplineMoveDistanceByPosition
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FVectorDouble&             NewPosition                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::UpdateSplineMoveDistanceByPosition(const struct FVectorDouble& NewPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "UpdateSplineMoveDistanceByPosition");

	Params::KuroSceneItemMoveComponent_UpdateSplineMoveDistanceByPosition Parms{};

	Parms.NewPosition = std::move(NewPosition);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.GetDistanceAlongSpline
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UKuroSceneItemMoveComponent::GetDistanceAlongSpline() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "GetDistanceAlongSpline");

	Params::KuroSceneItemMoveComponent_GetDistanceAlongSpline Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.GetSimpleRunState
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ESimpleRunState                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ESimpleRunState UKuroSceneItemMoveComponent::GetSimpleRunState() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "GetSimpleRunState");

	Params::KuroSceneItemMoveComponent_GetSimpleRunState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.GetSplineRunState
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ESplineRunState                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ESplineRunState UKuroSceneItemMoveComponent::GetSplineRunState() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "GetSplineRunState");

	Params::KuroSceneItemMoveComponent_GetSplineRunState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.IsMoving
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ConsiderSimpleWaitAsMoving                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::IsMoving(bool ConsiderSimpleWaitAsMoving) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "IsMoving");

	Params::KuroSceneItemMoveComponent_IsMoving Parms{};

	Parms.ConsiderSimpleWaitAsMoving = ConsiderSimpleWaitAsMoving;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.IsRotating
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UKuroSceneItemMoveComponent::IsRotating() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "IsRotating");

	Params::KuroSceneItemMoveComponent_IsRotating Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSceneItemMoveComponent.Kuro_GetGravityDirect
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector UKuroSceneItemMoveComponent::Kuro_GetGravityDirect() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSceneItemMoveComponent", "Kuro_GetGravityDirect");

	Params::KuroSceneItemMoveComponent_Kuro_GetGravityDirect Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroComponent.KuroSplineChainComponent.UpdateSplineChainIndex
// (Native, Protected, BlueprintCallable)

void UKuroSplineChainComponent::UpdateSplineChainIndex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroSplineChainComponent", "UpdateSplineChainIndex");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

