#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Dragon_AttackEvent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LS_Dragon_AttackEvent.SequenceDirector_C
// 0x0008 (0x0040 - 0x0038)
class LS_Dragon_AttackEvent::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);
	void 执行实体帧事件_3(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0, const class FString& Key, int32 EntityId);
	void 执行实体帧事件_2(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0, const class FString& Key, int32 EntityId);
	void 执行实体帧事件_1(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0, const class FString& Key, int32 EntityId);
	void 执行实体帧事件_0(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0, const class FString& Key, int32 EntityId);
	void SequenceEvent__ENTRYPOINTSequenceDirector_0(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_1(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_2(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_3(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_4(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_5(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_6(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_7(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_8(class ABP_KuroMasterSeqEvent_C* BP_KuroMasterSeqEvent_C_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass LS_Dragon_AttackEvent.SequenceDirector_C", true, "SequenceDirector_C">();
	}
	static class LS_Dragon_AttackEvent::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<LS_Dragon_AttackEvent::USequenceDirector_C>();
	}
};
static_assert(alignof(LS_Dragon_AttackEvent::USequenceDirector_C) == 0x000008, "Wrong alignment on LS_Dragon_AttackEvent::USequenceDirector_C");
static_assert(sizeof(LS_Dragon_AttackEvent::USequenceDirector_C) == 0x000040, "Wrong size on LS_Dragon_AttackEvent::USequenceDirector_C");
static_assert(offsetof(LS_Dragon_AttackEvent::USequenceDirector_C, UberGraphFrame) == 0x000038, "Member 'LS_Dragon_AttackEvent::USequenceDirector_C::UberGraphFrame' has a wrong offset!");

}

