#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PDA_HitMeshData

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PDA_HitMeshData.PDA_HitMeshData_C
// 0x0048 (0x0080 - 0x0038)
class UPDA_HitMeshData_C final : public UPrimaryDataAsset
{
public:
	class USkeletalMesh*                          HitSkeletalMesh;                                   // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             HitSkeletalMeshTransform;                          // 0x0040(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
	float                                         LastTime;                                          // 0x0070(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PDA_HitMeshData_C">();
	}
	static class UPDA_HitMeshData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPDA_HitMeshData_C>();
	}
};
static_assert(alignof(UPDA_HitMeshData_C) == 0x000010, "Wrong alignment on UPDA_HitMeshData_C");
static_assert(sizeof(UPDA_HitMeshData_C) == 0x000080, "Wrong size on UPDA_HitMeshData_C");
static_assert(offsetof(UPDA_HitMeshData_C, HitSkeletalMesh) == 0x000038, "Member 'UPDA_HitMeshData_C::HitSkeletalMesh' has a wrong offset!");
static_assert(offsetof(UPDA_HitMeshData_C, HitSkeletalMeshTransform) == 0x000040, "Member 'UPDA_HitMeshData_C::HitSkeletalMeshTransform' has a wrong offset!");
static_assert(offsetof(UPDA_HitMeshData_C, LastTime) == 0x000070, "Member 'UPDA_HitMeshData_C::LastTime' has a wrong offset!");

}

