#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SCameraModifier_Settings

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SCameraModifier_SettingsAdditional_structs.hpp"


namespace SDK
{

// UserDefinedStruct SCameraModifier_Settings.SCameraModifier_Settings
// 0x0118 (0x0118 - 0x0000)
struct FSCameraModifier_Settings final
{
public:
	int32                                         Priority_101_E74404724F7BCD1A815B9E8ECCEE64EC;     // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsModifiedArmLength_73_1686AE5842DD198072484BB2D855CAEB; // 0x0004(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ArmLength_74_192752C04380D5CAF2EB7E910DC5C9C5;     // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ArmLengthAdditional_75_3ED4AAB647CA6863AC2F9F9C1D48D229; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsModifiedArmRotation_76_570606324FC53E504274BDA6F59BD5C3; // 0x0010(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedArmRotationRoll_93_6CBBDC9043D8BF5E4EC3AB8E5473C625; // 0x0011(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedArmRotationPitch_94_6C16441D44C806A072B75DA882811D0C; // 0x0012(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedArmRotationYaw_95_FBE820DB4C8D5B75CEF242854F6F3774; // 0x0013(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               ArmRotation_77_B66F0D944DE7F4829886B997E0B1B89F;   // 0x0014(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               ArmRotationAdditional_78_A62C514641B680F97462AFB1C30145B6; // 0x0020(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedCameraOffset_79_43F688EC4B642A9CB92B0A8548187E16; // 0x002C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedCameraOffsetX_96_CCEBEC98498BB408B5BA0AB0BD15F414; // 0x002D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedCameraOffsetY_97_F5766DB146F88618F570C4A1F04A00F7; // 0x002E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsModifiedCameraOffsetZ_98_E6E0795348BE5A8749FB348FAD18D836; // 0x002F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CameraOffset_80_EB37D424428EBE421F9AAEB064701EAD;  // 0x0030(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CameraOffsetAdditional_81_DABDCE1243662E3E72DB62A0B56CEA53; // 0x003C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsModifiedCameraFov_53_1A8D869C4A5886B266452BBCB07BA93A; // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CameraFov_63_A418591F41F5EF0F2D3D19B8F9967FC9;     // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          OverrideCameraInput_59_0083E3164D765950CF70528078BF8218; // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          StopModifyOnMontageEnd_61_E5E58E644EDFAC8B5A53C08F375C0567; // 0x0051(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ResetFinalArmRotation_70_56DCE7204671EC361892799BE39735C5; // 0x0052(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsResetFinalArmRotationToSpecificPitch_214_7D5AF6E740BECE314B2A9091B86819BA; // 0x0053(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         ResetFinalArmRotationToSpecificPitch_218_D5485AE0497492082E1A0EACC346711E; // 0x0054(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsResetFinalArmRotationToSpecificYaw_216_CAA927574F691A4846483EAE0246D9D6; // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ResetFinalArmRotationToSpecificYaw_219_AB00A6984671B8AA7BA7B48F8A5737BC; // 0x005C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ResetFinalArmLength_72_0D8B0AFC4AA34A5415C9C6AC3D25FE4E; // 0x0060(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsResetFinalArmLengthToSpecificValue_204_D7743AE64930C1C3692EBC84B290FF1A; // 0x0061(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_62[0x2];                                       // 0x0062(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ResetFinalArmLengthToSpecificValue_207_E55092A1464EA622173DBCBEF34A8EF9; // 0x0064(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLockInput_86_CDDE4FA4418F23E40016969CB0D3623C;   // 0x0068(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsLerpArmLocation_111_5A5B00E645FAC54E063E8A93C1764D62; // 0x0069(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsSwitchModifier_113_0BCB940D4AB7A06EB3485D98E853EC0A; // 0x006A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          IsForcePlayModify_177_F5B3348F48031F5374647B85AB011967; // 0x006B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          StopModifyOnZoomInput_225_FDE50C654DD3E283ABF86C82C125979E; // 0x006C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSCameraModifier_SettingsAdditional    ModifySettingsAdditional_222_7DE2E3E64B6017435B7C1A8AA32C25C1; // 0x0070(0x00A8)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(FSCameraModifier_Settings) == 0x000008, "Wrong alignment on FSCameraModifier_Settings");
static_assert(sizeof(FSCameraModifier_Settings) == 0x000118, "Wrong size on FSCameraModifier_Settings");
static_assert(offsetof(FSCameraModifier_Settings, Priority_101_E74404724F7BCD1A815B9E8ECCEE64EC) == 0x000000, "Member 'FSCameraModifier_Settings::Priority_101_E74404724F7BCD1A815B9E8ECCEE64EC' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedArmLength_73_1686AE5842DD198072484BB2D855CAEB) == 0x000004, "Member 'FSCameraModifier_Settings::IsModifiedArmLength_73_1686AE5842DD198072484BB2D855CAEB' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ArmLength_74_192752C04380D5CAF2EB7E910DC5C9C5) == 0x000008, "Member 'FSCameraModifier_Settings::ArmLength_74_192752C04380D5CAF2EB7E910DC5C9C5' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ArmLengthAdditional_75_3ED4AAB647CA6863AC2F9F9C1D48D229) == 0x00000C, "Member 'FSCameraModifier_Settings::ArmLengthAdditional_75_3ED4AAB647CA6863AC2F9F9C1D48D229' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedArmRotation_76_570606324FC53E504274BDA6F59BD5C3) == 0x000010, "Member 'FSCameraModifier_Settings::IsModifiedArmRotation_76_570606324FC53E504274BDA6F59BD5C3' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedArmRotationRoll_93_6CBBDC9043D8BF5E4EC3AB8E5473C625) == 0x000011, "Member 'FSCameraModifier_Settings::IsModifiedArmRotationRoll_93_6CBBDC9043D8BF5E4EC3AB8E5473C625' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedArmRotationPitch_94_6C16441D44C806A072B75DA882811D0C) == 0x000012, "Member 'FSCameraModifier_Settings::IsModifiedArmRotationPitch_94_6C16441D44C806A072B75DA882811D0C' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedArmRotationYaw_95_FBE820DB4C8D5B75CEF242854F6F3774) == 0x000013, "Member 'FSCameraModifier_Settings::IsModifiedArmRotationYaw_95_FBE820DB4C8D5B75CEF242854F6F3774' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ArmRotation_77_B66F0D944DE7F4829886B997E0B1B89F) == 0x000014, "Member 'FSCameraModifier_Settings::ArmRotation_77_B66F0D944DE7F4829886B997E0B1B89F' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ArmRotationAdditional_78_A62C514641B680F97462AFB1C30145B6) == 0x000020, "Member 'FSCameraModifier_Settings::ArmRotationAdditional_78_A62C514641B680F97462AFB1C30145B6' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedCameraOffset_79_43F688EC4B642A9CB92B0A8548187E16) == 0x00002C, "Member 'FSCameraModifier_Settings::IsModifiedCameraOffset_79_43F688EC4B642A9CB92B0A8548187E16' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedCameraOffsetX_96_CCEBEC98498BB408B5BA0AB0BD15F414) == 0x00002D, "Member 'FSCameraModifier_Settings::IsModifiedCameraOffsetX_96_CCEBEC98498BB408B5BA0AB0BD15F414' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedCameraOffsetY_97_F5766DB146F88618F570C4A1F04A00F7) == 0x00002E, "Member 'FSCameraModifier_Settings::IsModifiedCameraOffsetY_97_F5766DB146F88618F570C4A1F04A00F7' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedCameraOffsetZ_98_E6E0795348BE5A8749FB348FAD18D836) == 0x00002F, "Member 'FSCameraModifier_Settings::IsModifiedCameraOffsetZ_98_E6E0795348BE5A8749FB348FAD18D836' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, CameraOffset_80_EB37D424428EBE421F9AAEB064701EAD) == 0x000030, "Member 'FSCameraModifier_Settings::CameraOffset_80_EB37D424428EBE421F9AAEB064701EAD' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, CameraOffsetAdditional_81_DABDCE1243662E3E72DB62A0B56CEA53) == 0x00003C, "Member 'FSCameraModifier_Settings::CameraOffsetAdditional_81_DABDCE1243662E3E72DB62A0B56CEA53' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsModifiedCameraFov_53_1A8D869C4A5886B266452BBCB07BA93A) == 0x000048, "Member 'FSCameraModifier_Settings::IsModifiedCameraFov_53_1A8D869C4A5886B266452BBCB07BA93A' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, CameraFov_63_A418591F41F5EF0F2D3D19B8F9967FC9) == 0x00004C, "Member 'FSCameraModifier_Settings::CameraFov_63_A418591F41F5EF0F2D3D19B8F9967FC9' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, OverrideCameraInput_59_0083E3164D765950CF70528078BF8218) == 0x000050, "Member 'FSCameraModifier_Settings::OverrideCameraInput_59_0083E3164D765950CF70528078BF8218' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, StopModifyOnMontageEnd_61_E5E58E644EDFAC8B5A53C08F375C0567) == 0x000051, "Member 'FSCameraModifier_Settings::StopModifyOnMontageEnd_61_E5E58E644EDFAC8B5A53C08F375C0567' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ResetFinalArmRotation_70_56DCE7204671EC361892799BE39735C5) == 0x000052, "Member 'FSCameraModifier_Settings::ResetFinalArmRotation_70_56DCE7204671EC361892799BE39735C5' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsResetFinalArmRotationToSpecificPitch_214_7D5AF6E740BECE314B2A9091B86819BA) == 0x000053, "Member 'FSCameraModifier_Settings::IsResetFinalArmRotationToSpecificPitch_214_7D5AF6E740BECE314B2A9091B86819BA' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ResetFinalArmRotationToSpecificPitch_218_D5485AE0497492082E1A0EACC346711E) == 0x000054, "Member 'FSCameraModifier_Settings::ResetFinalArmRotationToSpecificPitch_218_D5485AE0497492082E1A0EACC346711E' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsResetFinalArmRotationToSpecificYaw_216_CAA927574F691A4846483EAE0246D9D6) == 0x000058, "Member 'FSCameraModifier_Settings::IsResetFinalArmRotationToSpecificYaw_216_CAA927574F691A4846483EAE0246D9D6' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ResetFinalArmRotationToSpecificYaw_219_AB00A6984671B8AA7BA7B48F8A5737BC) == 0x00005C, "Member 'FSCameraModifier_Settings::ResetFinalArmRotationToSpecificYaw_219_AB00A6984671B8AA7BA7B48F8A5737BC' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ResetFinalArmLength_72_0D8B0AFC4AA34A5415C9C6AC3D25FE4E) == 0x000060, "Member 'FSCameraModifier_Settings::ResetFinalArmLength_72_0D8B0AFC4AA34A5415C9C6AC3D25FE4E' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsResetFinalArmLengthToSpecificValue_204_D7743AE64930C1C3692EBC84B290FF1A) == 0x000061, "Member 'FSCameraModifier_Settings::IsResetFinalArmLengthToSpecificValue_204_D7743AE64930C1C3692EBC84B290FF1A' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ResetFinalArmLengthToSpecificValue_207_E55092A1464EA622173DBCBEF34A8EF9) == 0x000064, "Member 'FSCameraModifier_Settings::ResetFinalArmLengthToSpecificValue_207_E55092A1464EA622173DBCBEF34A8EF9' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsLockInput_86_CDDE4FA4418F23E40016969CB0D3623C) == 0x000068, "Member 'FSCameraModifier_Settings::IsLockInput_86_CDDE4FA4418F23E40016969CB0D3623C' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsLerpArmLocation_111_5A5B00E645FAC54E063E8A93C1764D62) == 0x000069, "Member 'FSCameraModifier_Settings::IsLerpArmLocation_111_5A5B00E645FAC54E063E8A93C1764D62' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsSwitchModifier_113_0BCB940D4AB7A06EB3485D98E853EC0A) == 0x00006A, "Member 'FSCameraModifier_Settings::IsSwitchModifier_113_0BCB940D4AB7A06EB3485D98E853EC0A' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, IsForcePlayModify_177_F5B3348F48031F5374647B85AB011967) == 0x00006B, "Member 'FSCameraModifier_Settings::IsForcePlayModify_177_F5B3348F48031F5374647B85AB011967' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, StopModifyOnZoomInput_225_FDE50C654DD3E283ABF86C82C125979E) == 0x00006C, "Member 'FSCameraModifier_Settings::StopModifyOnZoomInput_225_FDE50C654DD3E283ABF86C82C125979E' has a wrong offset!");
static_assert(offsetof(FSCameraModifier_Settings, ModifySettingsAdditional_222_7DE2E3E64B6017435B7C1A8AA32C25C1) == 0x000070, "Member 'FSCameraModifier_Settings::ModifySettingsAdditional_222_7DE2E3E64B6017435B7C1A8AA32C25C1' has a wrong offset!");

}

